import 'package:get/get.dart';

class Languages extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US':{
      'Home': 'Home',
      "Random Anime Quote": "Random Anime Quote",
      "View a random anime quote": "View a random anime quote",
      "Random Anime":"Random Anime",
      "Get Information About a Random Anime":"Get Information About a Random Anime",
      "Random Anime Kick":"Random Anime Kick",
      "Get a Gif of Random Anime Kick":"Get a Gif of Random Anime Kick",
      "Random Anime Poke":"Random Anime Poke",
      "Get a gif of anime poking":"Get a gif of anime poking",
      "Random Anime Pat":"Random Anime Pat",
      "Get a gif of anime patting":"Get a gif of anime patting",
      "Random Anime Dance":"Random Anime Dance",
      "Get a gif of random anime dance":"Get a gif of random anime dance",
      "Random Anime Cuddle":"Random Anime Cuddle",
      "Get a gif of random anime cuddle moment":"Get a gif of random anime cuddle moment",
      "Random Anime HighFive":"Random Anime HighFive",
      "Get a gif of anime highfive":"Get a gif of anime highfive",
      "Random Anime Wink":"Random Anime Wink",
      "Get a gif of anime winking":"Get a gif of anime winking",
      "Random Anime Hug":"Random Anime Hug",
      "Get a gif of anime Hugging":"Get a gif of anime Hugging",
      "Random Anime Bonk":"Random Anime Bonk",
      "Get a gif of anime bonking":"Get a gif of anime bonking",
      "Random Anime Waifu":"Random Anime Waifu",
      "Get an image of anime waifu":"Get an image of anime waifu"
    },
    'hi_IN':{
      'Home': 'होम',
      "Random Anime Quote": "रैंडम एनीमे उद्धरण",
      "View a random anime quote": "एक यादृच्छिक एनीमे उद्धरण देखें",
      "Random Anime":"रैंडम एनीमे",
      "Get Information About a Random Anime":"रैंडम एनीमे के बारे में जानकारी प्राप्त करें",
      "Random Anime Kick":"रैंडम एनीमे किक",
      "Get a Gif of Random Anime Kick":"रैंडम एनीमे किक का जिफ़ प्राप्त करें",
      "Random Anime Poke":"रैंडम एनीमे पोक",
      "Get a gif of anime poking":"एनीमे पोकिंग का जिफ़ प्राप्त करें",
      "Random Anime Pat":"रैंडम एनीमे पैट",
      "Get a gif of anime patting":"एनीमे थपथपाने का जिफ़ प्राप्त करें",
      "Random Anime Dance":"रैंडम एनीमे डांस",
      "Get a gif of random anime dance":"यादृच्छिक एनीम नृत्य का एक जिफ प्राप्त करें",
      "Random Anime Cuddle":"रैंडम एनीमे कडल",
      "Get a gif of random anime cuddle moment":"रैंडम एनीमे कडल मोमेंट का जिफ़ प्राप्त करें",
      "Random Anime HighFive":"रैंडम एनीमे हाईफाइव",
      "Get a gif of anime highfive":"एनीमे हाईफाइव का जिफ प्राप्त करें",
      "Random Anime Wink":"रैंडम एनीमे विंक",
      "Get a gif of anime winking":"एनीम विंकिंग का एक जिफ प्राप्त करें",
      "Random Anime Hug":"रैंडम एनीमे हग",
      "Get a gif of anime Hugging":"एनीमे हगिंग का जिफ़ प्राप्त करें",
      "Random Anime Bonk":"रैंडम एनीमे बोंक",
      "Get a gif of anime bonking":"एनिमी बॉन्डिंग का जिफ़ प्राप्त करें",
      "Random Anime Waifu":"रैंडम एनीमे वाइफू",
      "Get an image of anime waifu":"एनीमे वाइफू की एक छवि प्राप्त करें"
    },
    'fr_FR':{
      'Home': 'Accueil',
      "Random Anime Quote": "Citation d'anime aléatoire",
      "View a random anime quote": "Voir une citation d'anime au hasard",
      "Random Anime":"Anime aléatoire",
      "Get Information About a Random Anime":"Obtenir des informations sur un anime aléatoire",
      "Random Anime Kick":"Coup de pied aléatoire dans l'anime",
      "Get a Gif of Random Anime Kick":"Obtenir un Gif d'un Anime Kick aléatoire",
      "Random Anime Poke":"Poke d'anime aléatoire",
      "Get a gif of anime poking":"Obtenir un gif d'anime poking",
      "Random Anime Pat":"Patte d'Anime aléatoire",
      "Get a gif of anime patting":"Obtenir un gif de l'anime en train de tapoter",
      "Random Anime Dance":"Danse d'anime aléatoire",
      "Get a gif of random anime dance":"Obtenir un gif d'une danse d'anime aléatoire",
      "Random Anime Cuddle":"Câlins d'anime aléatoires",
      "Get a gif of random anime cuddle moment":"Obtenir un gif d'un moment de câlin d'anime aléatoire",
      "Random Anime HighFive":"HighFive Anime aléatoire",
      "Get a gif of anime highfive":"Obtenir un gif de l'anime highfive",
      "Random Anime Wink":"Clin d'œil aléatoire à l'anime",
      "Get a gif of anime winking":"Obtenir un gif de l'anime faisant un clin d'œil",
      "Random Anime Hug":"Câlins d'anime aléatoires",
      "Get a gif of anime Hugging":"Obtenir un gif d'anime aléatoires",
      "Random Anime Bonk":"Anime Bonk aléatoire",
      "Get a gif of anime bonking":"Obtenir un gif d'un anime en train de baiser",
      "Random Anime Waifu":"Waifu d'anime aléatoire",
      "Get an image of anime waifu":"Obtenir une image de l'anime waifu"
    },
  };
}